### ISSUE TITLE
Exception thrown when trying to view Cache Manager

### ISSUE THREAD

**Issue by rasyadi** [JakobChristensen/Sitecore.Rocks#34]
**Environment Details**
OS: Windows 10
Visual Studio Version: Visual Studio 2015 with Update 3
Sitecore Rocks version: 2.0.45.0
Sitecore Platform version: 8.2 revision 160729

**Steps to reproduce**

1. In Sitecore Explorer, navigate to any item.
2. Right click to open context dialog, navigate to Tools > Caches.
3. The following exception thrown,
![sitecorerocktoolscache](https://cloud.githubusercontent.com/assets/147564/21876177/d79a42ce-d8bb-11e6-9ba4-cb0b284dea40.png)

**Expectation**
Cache Manager displayed.

**Comment by JakobChristensen** [comment]
Hi Rasyadi

Yes, I can reproduce this in 8.2

Unfortunately Sitecore CMS 8.2 contains breaking changes with no backwards compatibility, that makes it impossible to support cache management in both 8.2 and previous. 

The CacheManager class now uses the ICacheInfo interface instead of the Cache object.

The best we can do is to show a warning that Cache Management does not work in 8.2. When 8.2 is more widely adopted, we can flip the switch and support 8.2 and later instead.

**Comment by JakobChristensen** [comment]
Updated to Sitecore 8.2
