### ISSUE TITLE
Rocks will lock Sitecore.Kernel.dll when connected

### ISSUE THREAD

**Issue by Eldblom** [JakobChristensen/Sitecore.Rocks#48]
This is highly annoying when using a Publish project workflow through visual studio.

To recreate:

1. Setup Habitat
2. Connect a Habitat project module to Sitecore via Rocks
3. run "gulp" or do a Visual Studio publish on a project in Habitat

**Comment by JakobChristensen** [comment]
Rocks no longer locks Sitecore.Kernel to obtain the .NET Framework version.

This check was meant to prevent Rocks from automatically updating a website with assemblies which use a higher Framework version than the website.

Since this obtaining the framework version automatically is no longer possible, the framework version can be specified manually in the Connection Properties in the DotNetFrameworkVersion field. The default version is v10.0.0.
