### ISSUE TITLE
Where can I get the VSIX for v1.5.1.8 (for VS2013)

### ISSUE THREAD

**Issue by coldnebraskablue** [JakobChristensen/Sitecore.Rocks#55]
Hello, we're in a bit of a pickle and need to find the 1.5.1.8 VSIX for VS2013. SOme of our developers have it installed via VS Extensions and Updates, but that version is no longer available via this method. Also, the "Old Downloads" that I found only has v1.5.1.7. 

Is there a way of getting v1.5.1.8.vsix pls? It's kinda urgent, ta. 

Paul

**Comment by JakobChristensen** [comment]
Hi Paul

Hmm, odd that 1.5.1.8 is not on the old versions page - sorry about that.

I am on vacation, and do not access to my work station, but maybe you can hack it yourselves, since it is urgent.

On one of the machines that have the correct version installed, you can copy the Rocks files, make a few changes and zip it into a .vsix file, that can be installed on other machines.

Here is how I just did it on VS2017 and version 2.1.69.

1. On one of the machines with the correct version, open the Sitecore Start Page by clicking Main Menu | Sitecore | Sitecore Start Page.
2. On the Start Page to the left, select Sitecore Rocks and click Open Sitecore Rocks application folder in Windows Explorer. This is where all the Sitecore Rocks files are located.
3. Copy the files to another folder.
4. Unzip the attached file to the folder. The folder should now have a "[Content_Types].xml" file. 
[[Content_Types].zip](https://github.com/JakobChristensen/Sitecore.Rocks/files/1163116/Content_Types.zip)
5. Edit the extension.vsixmanifest and remove the <License> tag.
6. Your folder should look like the attached screenshot.
![image](https://user-images.githubusercontent.com/2310296/28429752-1cf1a220-6d7e-11e7-8902-fad1f6b35fc7.png)
7. Zip the folder to Rocks.zip.
8. Rename Rocks.zip to Rocks.vsix

Hope it works (and if it does, could you send it to me, so I can upload it when I get back).
